type: ACTION
language: PYTHON_3
name: Monitor BGP stats
description: Monitors CloudVision to ensure the number of BGP peers pre and post Change Control are the same, and will fail if they are different
file: script.py
static-params: []
dynamic-params:
  - name: DeviceID
    description: The device whose BGP stats will be monitored.
    required: true
    hidden: false
  - name: vrfs
    description: True/False flag to also monitor vrf BGP peers rather than just the device's BGP peers. Defaults to False
    required: false
    hidden: false
    default: "False"
  - name: expected_difference
    description: The expected difference between pre CC peers and current peers for the device. Positive numbers allow for adding splines, negative for retiring splines. Defaults to 0 (No difference allowed)
    required: false
    hidden: false
    default: "0"
  - name: check_wait
    description: Time to wait before checking the device's number of current peers to allow them to settle. Defaults to 60 seconds
    required: false
    hidden: false
    default: "60"
